import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Boxes, LayoutDashboard, Menu, PackagePlus, Plus, RefreshCw, X } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
const formatDate = (value) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '-';

async function request(path, options) {
  const response = await fetch(`${API_URL}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message || 'Permintaan gagal diproses.');
  return body;
}

function StatCard({ icon: Icon, label, value, accent }) {
  return <div className="rounded-2xl border border-[#e1e8e1] bg-white p-5 shadow-sm"><div className={`mb-6 flex h-10 w-10 items-center justify-center rounded-xl ${accent}`}><Icon size={19} /></div><p className="text-sm text-slate-500">{label}</p><p className="display mt-1 text-3xl font-bold text-[#17211b]">{value}</p></div>;
}

function BarangModal({ item, onClose, onSave }) {
  const [form, setForm] = useState(item || { nama_barang: '', stok_saat_ini: 0, stok_minimum: 0 });
  const update = (key, value) => setForm({ ...form, [key]: key === 'nama_barang' ? value : Number(value) });
  return <div className="fixed inset-0 z-20 flex items-center justify-center bg-[#17211b]/40 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Master barang</p><h2 className="display mt-1 text-2xl font-bold">{item ? 'Edit barang' : 'Tambah barang'}</h2></div><button onClick={onClose} aria-label="Tutup" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Nama barang<input value={form.nama_barang} onChange={(event) => update('nama_barang', event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-emerald-500" placeholder="Contoh: Beras 5 kg" /></label><div className="grid grid-cols-2 gap-4"><label className="block text-sm font-semibold">Stok saat ini<input type="number" min="0" value={form.stok_saat_ini} onChange={(event) => update('stok_saat_ini', event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><label className="block text-sm font-semibold">Stok minimum<input type="number" min="0" value={form.stok_minimum} onChange={(event) => update('stok_minimum', event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label></div></div><div className="mt-7 flex justify-end gap-3"><button onClick={onClose} className="rounded-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:bg-slate-100">Batal</button><button onClick={() => onSave(form)} className="rounded-xl bg-[#198754] px-5 py-3 text-sm font-bold text-white hover:bg-[#126b41]">Simpan barang</button></div></div></div>;
}

export default function App() {
  const [page, setPage] = useState('dashboard'); const [barang, setBarang] = useState([]); const [lowStock, setLowStock] = useState([]); const [transactions, setTransactions] = useState([]); const [modal, setModal] = useState(null); const [notice, setNotice] = useState(null); const [loading, setLoading] = useState(true); const [mobileNav, setMobileNav] = useState(false);
  const [transaction, setTransaction] = useState({ id_barang: '', jenis_transaksi: 'masuk', jumlah: 1 });
  const load = async () => { setLoading(true); try { const [items, low, history] = await Promise.all([request('/barang'), request('/barang/low-stock'), request('/transaksi')]); setBarang(items); setLowStock(low); setTransactions(history); if (!transaction.id_barang && items[0]) setTransaction({ ...transaction, id_barang: items[0].id_barang }); } catch (error) { setNotice({ type: 'error', message: error.message }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const saveItem = async (form) => { try { await request(modal?.id_barang ? `/barang/${modal.id_barang}` : '/barang', { method: modal?.id_barang ? 'PUT' : 'POST', body: JSON.stringify(form) }); setModal(null); setNotice({ type: 'success', message: 'Data barang berhasil disimpan.' }); load(); } catch (error) { setNotice({ type: 'error', message: error.message }); } };
  const saveTransaction = async (event) => { event.preventDefault(); try { await request('/transaksi', { method: 'POST', body: JSON.stringify(transaction) }); setNotice({ type: 'success', message: 'Transaksi berhasil dicatat dan stok diperbarui.' }); setTransaction({ ...transaction, jumlah: 1 }); load(); } catch (error) { setNotice({ type: 'error', message: error.message }); } };
  const nav = [{ key: 'dashboard', label: 'Ringkasan', icon: LayoutDashboard }, { key: 'barang', label: 'Master Barang', icon: Boxes }, { key: 'transaksi', label: 'Transaksi In / Out', icon: PackagePlus }, { key: 'riwayat', label: 'Riwayat Transaksi', icon: RefreshCw }];
  const title = nav.find((item) => item.key === page)?.label;
  return <div className="min-h-screen bg-[#f5f7f4]"><aside className={`fixed inset-y-0 left-0 z-10 w-64 border-r border-[#dfe8df] bg-[#eef4ed] p-6 transition-transform md:translate-x-0 ${mobileNav ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#173f2a] text-white"><Boxes size={21} /></div><div><p className="display font-bold">Warung Stok</p><p className="text-xs text-slate-500">Manajemen inventaris</p></div></div><nav className="mt-12 space-y-2">{nav.map(({ key, label, icon: Icon }) => <button key={key} onClick={() => { setPage(key); setMobileNav(false); }} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${page === key ? 'bg-[#173f2a] text-white shadow-md' : 'text-slate-600 hover:bg-white'}`}><Icon size={18} />{label}</button>)}</nav><div className="grain absolute bottom-0 left-0 right-0 h-40 opacity-60" /></aside><main className="md:ml-64"><header className="flex items-center justify-between border-b border-[#e1e8e1] bg-white/80 px-5 py-4 backdrop-blur md:px-10"><button onClick={() => setMobileNav(!mobileNav)} className="rounded-lg p-2 md:hidden"><Menu size={21} /></button><div className="hidden md:block"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Sistem Manajemen</p><h1 className="display mt-1 text-xl font-bold">{title}</h1></div><button onClick={load} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /> Segarkan</button></header><div className="mx-auto max-w-7xl p-5 md:p-10">{notice && <div className={`mb-6 flex items-center justify-between rounded-xl border p-4 text-sm font-semibold ${notice.type === 'error' ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{notice.message}<button onClick={() => setNotice(null)}><X size={16} /></button></div>}{page === 'dashboard' && <Dashboard lowStock={lowStock} barang={barang} transactions={transactions} />} {page === 'barang' && <BarangPage barang={barang} onAdd={() => setModal({})} onEdit={setModal} />} {page === 'transaksi' && <TransactionPage barang={barang} transaction={transaction} setTransaction={setTransaction} onSubmit={saveTransaction} />} {page === 'riwayat' && <History transactions={transactions} />}</div></main>{modal && <BarangModal item={modal.id_barang ? modal : null} onClose={() => setModal(null)} onSave={saveItem} />}</div>;
}

function Dashboard({ lowStock, barang, transactions }) { return <><div className="mb-8"><p className="text-sm text-slate-500">Selamat datang kembali,</p><h2 className="display mt-1 text-3xl font-bold">Pantau warungmu hari ini.</h2></div><div className="grid gap-4 sm:grid-cols-3"><StatCard icon={Boxes} label="Total barang" value={barang.length} accent="bg-emerald-100 text-emerald-700" /><StatCard icon={ArrowDownToLine} label="Transaksi masuk" value={transactions.filter((item) => item.jenis_transaksi === 'masuk').length} accent="bg-blue-100 text-blue-700" /><StatCard icon={ArrowUpFromLine} label="Transaksi keluar" value={transactions.filter((item) => item.jenis_transaksi === 'keluar').length} accent="bg-orange-100 text-orange-700" /></div><section className="mt-8 rounded-2xl border border-red-100 bg-[#fffaf8] p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-red-100 text-red-600"><AlertTriangle size={21} /></div><div><h3 className="display text-lg font-bold">Perlu perhatian</h3><p className="mt-1 text-sm text-slate-500">{lowStock.length ? `${lowStock.length} barang menyentuh batas stok minimum.` : 'Semua stok berada di atas batas minimum.'}</p></div></div>{lowStock.length > 0 && <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{lowStock.map((item) => <div key={item.id_barang} className="flex items-center justify-between rounded-xl border border-red-100 bg-white p-4"><span className="font-semibold">{item.nama_barang}</span><span className="rounded-lg bg-red-50 px-2 py-1 text-sm font-bold text-red-600">{item.stok_saat_ini} / {item.stok_minimum}</span></div>)}</div>}</section></>; }

function BarangPage({ barang, onAdd, onEdit }) { return <><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">Katalog inventaris</p><h2 className="display mt-1 text-3xl font-bold">Daftar barang</h2></div><button onClick={onAdd} className="flex items-center gap-2 rounded-xl bg-[#198754] px-4 py-3 text-sm font-bold text-white hover:bg-[#126b41]"><Plus size={18} /> Tambah barang</button></div><div className="overflow-hidden rounded-2xl border border-[#e1e8e1] bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="border-b bg-[#f8faf8] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Nama barang</th><th className="px-5 py-4">Stok saat ini</th><th className="px-5 py-4">Batas minimum</th><th className="px-5 py-4">Status</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y divide-slate-100">{barang.map((item) => <tr key={item.id_barang}><td className="px-5 py-4 font-semibold">{item.nama_barang}</td><td className="px-5 py-4">{item.stok_saat_ini}</td><td className="px-5 py-4">{item.stok_minimum}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.stok_saat_ini <= item.stok_minimum ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-700'}`}>{item.stok_saat_ini <= item.stok_minimum ? 'Stok rendah' : 'Aman'}</span></td><td className="px-5 py-4 text-right"><button onClick={() => onEdit(item)} className="font-bold text-emerald-700 hover:underline">Edit</button></td></tr>)}</tbody></table>{!barang.length && <p className="p-10 text-center text-slate-500">Belum ada barang terdaftar.</p>}</div></>; }

function TransactionPage({ barang, transaction, setTransaction, onSubmit }) { return <div className="max-w-2xl"><p className="text-sm text-slate-500">Catat pergerakan persediaan</p><h2 className="display mt-1 text-3xl font-bold">Transaksi stok</h2><form onSubmit={onSubmit} className="mt-8 rounded-2xl border border-[#e1e8e1] bg-white p-6 shadow-sm md:p-8"><label className="block text-sm font-semibold">Pilih barang<select required value={transaction.id_barang} onChange={(event) => setTransaction({ ...transaction, id_barang: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">Pilih barang...</option>{barang.map((item) => <option key={item.id_barang} value={item.id_barang}>{item.nama_barang} (stok: {item.stok_saat_ini})</option>)}</select></label><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold">Jenis transaksi<select value={transaction.jenis_transaksi} onChange={(event) => setTransaction({ ...transaction, jenis_transaksi: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="masuk">Barang masuk</option><option value="keluar">Barang keluar</option></select></label><label className="block text-sm font-semibold">Jumlah<input required min="1" type="number" value={transaction.jumlah} onChange={(event) => setTransaction({ ...transaction, jumlah: Number(event.target.value) })} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label></div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-[#173f2a] px-5 py-3 font-bold text-white hover:bg-[#0e2d1d]"><PackagePlus size={18} /> Simpan transaksi</button></form></div>; }

function History({ transactions }) { return <><div className="mb-7"><p className="text-sm text-slate-500">Jejak aktivitas stok</p><h2 className="display mt-1 text-3xl font-bold">Riwayat transaksi</h2></div><div className="overflow-hidden rounded-2xl border border-[#e1e8e1] bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="border-b bg-[#f8faf8] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Waktu</th><th className="px-5 py-4">Barang</th><th className="px-5 py-4">Jenis</th><th className="px-5 py-4">Jumlah</th></tr></thead><tbody className="divide-y divide-slate-100">{transactions.map((item) => <tr key={item.id_transaksi}><td className="px-5 py-4 text-slate-500">{formatDate(item.created_at)}</td><td className="px-5 py-4 font-semibold">{item.tabel_barang?.nama_barang || 'Barang dihapus'}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.jenis_transaksi === 'masuk' ? 'bg-blue-50 text-blue-700' : 'bg-orange-50 text-orange-700'}`}>{item.jenis_transaksi === 'masuk' ? 'Masuk' : 'Keluar'}</span></td><td className="px-5 py-4 font-bold">{item.jumlah}</td></tr>)}</tbody></table>{!transactions.length && <p className="p-10 text-center text-slate-500">Belum ada transaksi.</p>}</div></>; }